### ISSUE TITLE
about how to use the  'on-infinite-scroll'

### ISSUE THREAD

**Issue by Henry0126** [frankdiox/OnsenUI-YouTube#2]
@frankdiox  I read your demo and still cant understand how to use the 'ng-infinite-scroll' in your project.
here is how I user it:
 html:
![image](https://cloud.githubusercontent.com/assets/25029204/21801935/b50fb904-d75e-11e6-90ba-0256a570f829.png)

js:$scope.images = [1, 2, 3, 4, 5, 6, 7, 8];
   $scope.loadMore = function() {
        var last = $scope.images[$scope.images.length - 1];
        for(var i = 1; i <= 8; i++) {
            $scope.images.push(last + i);
        }
    };

it works only I scroll to the bottom once; And I dont know how to use 'on-infinite-scroll' ,it always result a error 'onInfiniteScroll must be a function or null'

**Comment by frandiox** [comment]
@Henry0126 You should use `ng-infinite-scroll` instead of `on-infinite-scroll`. And remove the single quotes since it expects a function, not a string. [L1](https://github.com/frankdiox/OnsenUI-YouTube/blob/master/html/search.html#L1) `ng-infinite-scroll="loadMore"`.

**Comment by Henry0126** [comment]
@frankdiox I'm sorry that I paste the wrong code,here is the right :
![image](https://cloud.githubusercontent.com/assets/25029204/21803314/7f2663b4-d764-11e6-9944-266edd26325f.png)
It only works once when I scroll to the bottom .
And I want to user 'on-infinite-scroll' but dont know how to use

**Comment by frandiox** [comment]
@Henry0126 Are you using the latest version of Onsen UI? (2.0.5)

**Comment by Henry0126** [comment]
@frankdiox  no, the version  I'm using is 2.0.4 . the  **ng-infinite-scroll**   works but only the first time. 
I want to use **on-infinite-scroll**  instead  but it result an error every time.

**Comment by frandiox** [comment]
@Henry0126 Try 2.0.5 since there was some fix related to it. `on-infinite-scroll` does not work with AngularJS scopes. The way to use it is providing a global path like `on-infinite-scroll="window.myFunction"` or changing the element property instead of the attribute: `document.querySelector('#myPage').onInfiniteScroll = function() { ... }`.

Also, the function receives a [`done` callback that must be called when it finishes](https://github.com/frankdiox/OnsenUI-YouTube/blob/master/js/controllers.js#L47).

**Comment by Henry0126** [comment]
Thank you very much for your patient reply and I will try 2.0.5.
